#!/bin/sh
# hilow -- A simple number-guessing game

# include library.s
. library.sh

biggest=100				# maximum number possible
guess=0					# guessed by player
guesses=0				# number of guesses made
number=$(( $$ % $biggest ))		# random number, between 1 and $biggest

while [ $guess -ne $number ] ; do
  echo "Please enter a number."
  echon "Guess? " ; read guess
  
  # While not a valid int request it
  while ! `validint $guess 0 100`; do
     echo "Please enter a number. Use ^C to quit."
     echon "Guess? " ; read guess
  done

  if [ "$guess" -lt $number ] ; then
    echo "... bigger!"
  elif [ "$guess" -gt $number ] ; then
    echo "... smaller!"
  fi
  guesses=$(( $guesses + 1 ))
done

echo "Right!! Guessed $number in $guesses guesses."

exit 0
